services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 2026_1_php_web_server
    networks:
      - webnet
      - dbnet
    depends_on:
      - mariadb
    volumes:
      - .:/var/www/html

  mariadb:
    image: mariadb:10.6.20
    container_name: 2026_1_php_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: 2026_1_php
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - dbnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 2026_1_php_phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8080:80
    networks:
      - dbnet

  nginx:
    image: nginx:latest
    networks:
      - webnet
    ports:
      - 8000:80
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - web

networks:
  webnet:
  dbnet:

volumes:
  mariadb_data:
